<?php
/* 
* Copyright (C) www.vtiger.com. All rights reserved.
* @license Proprietary
*/





$languageStrings = array(
    'LBL_PUBLISHER' => 'ناشر',
    'LBL_LICENSE' => 'مجوز',
    'LBL_PUBLISHED_ON' => 'منتشر شده در',
    'LBL_INSTALL' => 'نصب',
    'LBL_UPGRADE' => 'به روز رسانی',
    'LBL_VERSION' => 'نسخه',
    'LBL_DECLINE' => 'کاهش',
    'LBL_ACCEPT_AND_INSTALL' => 'قبول و نصب',
    'LBL_OK' => 'تایید',
    'LBL_EXTENSION_NOT_COMPATABLE' => 'این افزونه سازگار نیست',
    'LBL_INVALID_FILE' => 'فایل نا معتبر',
    'LBL_NO_LICENSE_PROVIDED' => 'مجوزی فراهم نشد',
    'LBL_INSTALLATION' => 'در حال نصب',
    'LBL_FAILED' => 'ناموفق',
    'LBL_SUCCESSFULL' => 'موفق',
    'LBL_INSTALLATION_LOG' => 'لاگ نصب',
    'LBL_UPDATED_MODULE' => 'ماژول با موفقیت به روز شد.',
    'LBL_UPDATING_MODULE' => 'به روزرسانی ماژول',
    'LBL_MARKET_PLACE' => 'بازارگاه ',

    //Extension Store translations
    'LBL_VTIGER_EXTENSION_STORE' => 'فروشگاه افزونه ویتایگر',
    'LBL_SEARCH_FOR_AN_EXTENSION' => 'جستجو برای افزونه..',
    'LBL_DOWNLOADS' => 'دانلودها',
    'LBL_NO_EXTENSIONS_FOUND' => 'هیچ افزونه ایی یافت نشد',
    'LBL_REGISTER_TO_MARKET_PLACE' => 'ثبت نام دربازار ',
    'LBL_MARKETPLACE_REGISTRATION' => 'ثبت نام بازار ',
    'LBL_MARKETPLACE_LOGIN' => 'ورود به بازار',
    'LBL_NEW_TO_MARKETPLCAE' => 'جدید در بازار؟',
    'LBL_CREATE_AN_ACCOUNT' => 'ایجاد حساب جدید',
    'LBL_SETUP_CARD_DETAILS' => 'تنظیم جزییات کارت',
    'LBL_SETUP_CARD' => 'تنظیم کارت',
    'LBL_CARD_NUMBER' => 'شماره کارت',
    'LBL_EXP_MONTH' => 'ماه انقضا',
    'LBL_EXP_YEAR' => 'سال انقضا',
    'LBL_CVC_CODE' => 'کد CVC',
    'LBL_RESET' => 'بازنشانی',
    'LBL_EXTENSION_STORE' => 'فروشگاه افزونه',
    'LBL_INSTALLED' => 'نصب شده',
    'LBL_UPDATE_CARD_DETAILS' => 'به روزرسانی جزییات کارت',
    'LBL_BY' => 'توسط',
    'LBL_RATINGS' => 'امتیازدهی',
    'LBL_DESCRIPTION' => 'شرح',
    'LBL_AUTHOR_INFORMATION' => 'اطلاعات نویسنده',
    'LBL_AUTHOR_NAME' => 'نام نویسنده',
    'LBL_PHONE' => 'تلفن',
    'LBL_EMAIL' => 'ایمیل',
    'LBL_SCREEN_SHOTS' => 'تصویر',
    'LBL_CUSTOMER_RATINGS' => 'امتیازدهی مشتری',
    'LBL_CUSTOMER_REVIEWS' => 'مشاهدات مشتری',
    'LBL_WRITE_A_REVIEW' => 'نوشتن نظر',
    'LBL_CUSTOMER_REVIEW' => 'نظر مشتری',
    'LBL_REVIEW' => 'نظر',
    'LBL_CUSTOMERS_REVIEWED' => 'نظرات مشتری',
    'LBL_SINGLE_CUSTOMER_REVIEWED' => 'نظرات یک مشتری',
    'LBL_INSTALLATION_FAILED' => 'نصب ناموفق',
    'LBL_SUCCESSFULL_INSTALLATION' => 'نصب موفق',
    'LBL_INSTALL_FROM_ZIP' => 'نصب از فایل زیپ',
    'LBL_MORE_DETAILS' => 'جزییات بیشتر',
    'Install' => 'نصب',
    'Upgrade' => 'به روزرسانی',
    'LBL_RATE_IT' => 'امتیاز',
    'LBL_UNINSTALL' => 'عزل',
    'LBL_LAUNCH' => 'راه اندازی',
    'LBL_SIGN_UP_FOR_FREE' => 'ورود مجانی',
    'LBL_EMAIL_ADDRESS' => 'آدرس ایمیل',
    'LBL_FIRST_NAME' => 'نام',
    'LBL_LAST_NAME' => 'نام خانوادگی',
    'LBL_COMPANY_NAME' => 'نام شرکت',
    'LBL_PASSWORD' => 'کلمه عبور',
    'LBL_CONFIRM_PASSWORD' => 'تایید کلمه عبور',
    'LBL_REGISTER' => 'ثبت نام',
    'LBL_EXTENSION_STORE_LOGIN' => 'ورود به فروشگاه افزونه',
    'LBL_REMEMBER_ME' => 'مرا به خاطر بسپار',
    'LBL_TRY_IT' => 'تلاش',
    'LBL_TRIAL_INSTALLED' => 'نصب موقت',
    'LBL_BUY' => 'خرید',
    'LBL_LOGIN_TO_MARKET_PLACE' => 'ورود به بازار',
    'LBL_LOGIN' => 'ورود',
    'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'لطفا لودر افزونه را نصب کنید',
    'LBL_INSTALL_EXTENSION_LOADER' => 'نصب لودر افزونه',
    'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'برای ادامه لطفا فروشگاه افزونه را نصب کنید',
    'LBL_DOWNLOAD' => 'دانلود',
    'LBL_COMPATIABLE_EXTENSION' => 'فعال سازی zend_extension',
    'LBL_MORE_DETAILS_ON_INSTALLATION' => 'برای جزییات بیشتر در نصب',
    'LBL_READ_HERE' => 'ادامه مطلب',
    'LBL_REVIEWS' => 'نظرات',
    'LBL_SIGNUP_FOR_MARKET_PLACE' => 'ورود به بازار',
    'LBL_UNAUTHORIZED' => 'ناشناخته',
    'LBL_EXPIRY_DATE' => 'تاریخ انقضا',
    'LBL_LOGOUT' => 'خروج',

    'firstname' => 'نام',
    'lastname' => 'نام خانوادگی',
    'email' => 'ایمیل',
    'company' => 'شرکت',
    'Phone' => 'تلفن',
    'Website' => 'وب سایت',
    'LBL_SECURITY_CODE' => 'کد امنیتی',
    'LBL_WHAT_IS_SECURITY_CODE' => 'کد امنیتی چیست؟',
    'LBL_CARD_NUMBER_PLACEHOLDER' => '16 رقم روی کارت',
    'LBL_SECURITY_CODE_HELP_CONTENT' => 'The CVV Number(Card Verification Value) on your credit/debit card is a 3 digit number on VISA®, MasterCard® etc.. branded credit/debit cards.',
    'LBL_ENTER_REGISTERED_EMAIL' => 'ایمیل ثبت شده را وارد کنید',
    'LBL_RESET_PASSWORD_LINK_EMAILED' => 'لینک ریست پسورد ایمیل شد ',
    'LBL_FORGOT_PASSWORD' => 'فراموشی رمز',
    'LBL_ALREADY_INSTALLED_MODULE_BUILDER' => 'اخیرا با module builder ساخته شده ',
    'LBL_REVIEW_RESTRICTED' => 'مرور محدود شده است',
);
$jsLanguageStrings = array(
    'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION' => 'برای نصب این افزونه جزییات کارت را تنظیم کنید',
    'JS_UPDATE_CARD_DETAILS' => 'به روزرسانی جزییات کارت',
    'JS_ON' => 'در',
    'JS_RATINGS' => 'امتیازدهی',
    'JS_INSTALLED' => 'نصب شده',
    'JS_TRIAL_INSTALLED' => 'نصب موقت',
    'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'لطفا لودر افزونه را برای نصب این افزونه از لینک زیر نصب کنید',
    'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => 'لطفا برای نصب افزونه به بازار وارد شوید',
    'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => 'لطفا برای نصب افزونه جزییات کارت را تنظیم کنید',
    'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => 'لطفا برای عزل افزونه به بازار وارد شوید',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_INSTALL_THIS_EXTENSION' => 'آیا از نصب این افزونه مطمئن هستید؟',
    'JS_CARD_DETAILS_UPDATED' => 'جزییات کارت به روز شد!',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT_FROM_EXTENSION' => 'آیا مطمئن هستید میخواهید از این افزونه خارج شوید؟',
    'JS_PASSWORDS_MISMATCH' => "پسوردها صحیح نیستند! ",
    'JS_ARE_YOU_SURE_UNINSTALL' => 'آیا از حذف این افزونه مطمئن هستید؟',
    'JS_ARE_YOU_SURE_INSTALL' => 'آیا از نصب این افزونه مطمئن هستید؟ ',
);
