<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Calendar' => 'انجام دادن',
	'Checkbox' => 'جعبه انتخاب ',
	'Currency'=>'ارز',
	'Date'=>'تاریخ',
	'Decimal'=>'اعشاری',
	'Email'=>'ایمیل',
	'Integer'=>'عدد صحیح',
	'LayoutEditor' => 'قالب ویرایشگر',
	'LBL_ACTIONS' => 'فعالیت ها',
	'LBL_ACTIVE' => 'فعال',
	'LBL_ADD_AFTER' => 'افزودن بعد از',
	'LBL_ADD_CUSTOM_BLOCK' => 'افزودن بلوک سفارشی',
	'LBL_ADD_CUSTOM_FIELD' => 'افزودن فیلد سفارشی',
	'LBL_ADD_MODULE_INFO' => 'انتخاب ماژول از ماژول های برداشته شده برای افزودن به فهرست',
	'LBL_ALWAYS_SHOW' => 'همیشه نمایش بده',
	'LBL_ARRANGE_RELATED_LIST' => 'مرتب سازی فهرست مرتبط',
	'LBL_ARRANGE_RELATED_TABS' => 'مرتب سازی تب های مرتبط',
	'LBL_BLOCK_NAME' => 'نام بلوک',
	'LBL_CLICK_HERE_TO_EDIT' => 'برای ویرایش کلیک کنید',
	'LBL_CREATE_CUSTOM_FIELD' => 'ایجاد فیلد سفارشی',
	'LBL_DECIMALS' => 'اعشاری',
	'LBL_DEFAULT_VALUE' => 'مقدار پیشفرض',
	'LBL_DELETE_CUSTOM_BLOCK' => 'حذف بلوک سفارشی',
	'LBL_DETAILVIEW_LAYOUT' => 'جزییات مشاهده چیدمان',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'فیلد تکراری موجود است',
	'LBL_DUPLICATES_EXIST' => 'نام بلوک موجود است',
	'LBL_ENTER_PICKLIST_VALUES' => 'مقادیر فهرست انتخابی را وارد کنید..',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'فیلدها و چیدمان ویرایشگر',
	'LBL_INACTIVE_FIELDS' => 'فیلدهای غیرفعال', //Duplicated key-value pairs
	'LBL_LABEL_NAME' => 'نام برچسب',
	'LBL_LENGTH' => 'طول',
	'LBL_MANDATORY_FIELD' => 'فیلد الزامی',
	'LBL_MASS_EDIT' => 'توده ویرایش',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'فهرست انتخابی بدون نقش',
	'LBL_NO_RELATED_INFORMATION' => 'اطلاعات نامربوط',
	'LBL_PICKLIST_VALUES' => 'مقادیر فهرست انتخابی',
	'LBL_QUICK_CREATE' => 'ایجاد سریع',
	'LBL_REACTIVATE' => 'فعال سازی مجدد',
	'LBL_RELATED_LIST_INFO' => 'برای مرتب سازی فهرست ماژول را بکشید و اینجا بیندازید',
	'LBL_REMOVE_INFO' => 'برای برداشتن ماژول از فهرست آیکون بستن را کلیک کنید',
	'LBL_ROLE_BASED_PICKLIST' => 'فهرست انتخابی نقش پایه ای',
	'LBL_SAVE_FIELD_SEQUENCE' => 'ذخیره دنباله فیلد',
	'LBL_SELECT_FIELD_TYPE' => 'انتخاب نوع فیلد',
	'LBL_SELECT_MODULE' => 'انتخاب ماژول..',
	'LBL_SELECT_MODULE_TO_ADD' => 'انتخاب ماژول برای افزودن ',
	'LBL_SUMMARY_FIELD' => 'مشاهده خلاصه',
	'LBL_WRONG_FIELD_TYPE' => 'نوع فیلد اشتباه',
	'MultiSelectCombo'=>'جعبه چند انتخابی ',
	'Percent'=>'درصد',
	'Phone'=>'تلفن ',
	'PickList'=>'فهرست انتخابی ',
	'Skype'=>'اسکایپ',
	'TextArea' => 'محدوده متنی',
	'Text'=>'متن',
	'Time'=>'زمان ',
	'URL' => 'آدرس اینترنتی ',
);

$jsLanguageStrings = array(
	'JS_BLOCK_NAME_EXISTS' => 'نام بلوک موجود است',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'دنباله بلوک ها به روز شد',
	'JS_BLOCK_VISIBILITY_HIDE' => 'فعال سازی پنهان کردن بلاک',
	'JS_BLOCK_VISIBILITY_SHOW' => 'فعال سازی نمایش بلاک',
	'JS_CUSTOM_BLOCK_ADDED' => 'بلاک سفارشی جدید افزوده شد',
	'JS_CUSTOM_BLOCK_DELETED' => 'بلوک سفارشی حذف شده',
	'JS_CUSTOM_FIELD_ADDED' => 'فیلد سفارشی جدید اضافه شده',
	'JS_CUSTOM_FIELD_DELETED' => 'فیلد سفارشی حذف شده',
	'JS_DUPLICATES_VALUES_FOUND' => 'تشخیص مقادیر تکراری ',
	'JS_FIELD_DETAILS_SAVED' => 'جزییات فیلد ذخیره شده',
	'JS_FIELD_SEQUENCE_UPDATED' => 'دنباله فیلد به روز شده',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'طول باید کمتر یا مساوی باشد با',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'بدون فیلد غیرفعال',
	'JS_NOT_ALLOWED' => 'مجاز نیست',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'اعشار باید در بازه 2 تا 5 باشد',
	'JS_RELATED_INFO_SAVED' => 'اطلاعات مرتبط ذخیره شده',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'برای به روزشدن تغییرات را ذخیره کنید',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'فیلدهای بازسازی شده منتخب',
	'JS_SPECIAL_CHARACTERS' => 'کاراکتر خاص مانند',
);
