<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'action' => 'فعال',
	'ADD_RULES' => 'افزودن قانون',
	'After Scan'                   => 'بعد از اسکن'                  ,
	'ALL' => 'همه÷',
	'Begins With' => 'شروع',
	'body' => 'بدنه',
	'Connect URL'                  => 'آدرس اتصال '                 , 
	'Contains' => 'شامل',
	'CREATE_Accounts_SUBJECT' => 'ایجاد سازمان ',
	'CREATE_Contacts_SUBJECT' => 'ایجاد مخاطب',
	'CREATE_HelpDesk_FROM' => 'ایجاد تیکت',
	'CREATE_Leads_SUBJECT' => 'ایجاد سرنخ فروش ',
	'Do Not Validate SSL Certificate'=> 'گواهی SSL نامعتبر ',
	'Ends With' => 'پایان',
	'Equals' => 'مساوی',
	'fromaddress' => 'از',
	'LBL_ACTION' => 'فعال',
	'LBL_ACTIONS' => 'عملیات',
	'LBL_ADDING_NEW_MAILBOX' => 'افزودن صندوق ایمیل جدید',
	'LBL_ADD_RECORD' => 'افزودن صندوق ایمیل ',
	'LBL_ADD_RULE' => 'افزودن قانون',
	'LBL_ALL_CONDITIONS' => 'تمام معیارها',
	'LBL_ALL_MESSAGES_FROM_LAST_SCAN' => 'تمام پیام ها از آخرین اسکن',
	'LBL_ANY_CONDITIOn' => 'هر معیاری',
	'LBL_BACK_TO_MAILBOXES' => 'بازگشت به صندوق ایمیل ',
	'LBL_BODY' => 'بدنه',
	'LBL_CONDITIONS' => 'شرایط',
	'LBL_CONNECTION_ERROR' => 'خطا در ارتباط با صندوق ایمیل. ارتباط اینترنت را چک کنید.', 
	'LBL_CONNECTION_TO_MAILBOX_FAILED' => 'شکست در ارتباط با صندوق ایمیل',
	'LBL_CONVERT_EMAILS_TO_RESPECTIVE_RECORDS' => 'تبدیل ایمیل به رکوردهای مربوطه',
	'LBL_CREATE_MAILBOX' => 'ایجاد صندوق ایمیل ',
	'LBL_CREATE_MAILBOX_NOW' => 'ایجاد صندوق ایمیل ',
	'LBL_DELETED_SUCCESSFULLY' => 'حذف موفق', //Duplicated key-value pair
	'LBL_DELETE_RULE' => 'حذف نقش',
	'LBL_DISABLE' =>'غیرفعال',
	'LBL_DO_NOT_VALIDATE_SSL_CERTIFICATE' => 'گواهی SSL معتبر نیست',
	'LBL_DRAG_AND_DROP_BLOCK_TO_PRIORITISE_THE_RULE' => 'برای اولویت بندی قوانین بلوک ها را گرفته و بکشید',
	'LBL_EDIT_MAILBOX' => 'ویرایش صندوق ایمیل ',
	'LBL_ENABLE' => 'فعال',
	'LBL_FINISH' => 'پایان',
	'LBL_FOLDERS_INFO_IS_EMPTY' => 'اطلاعات فولدر خالی است',
	'LBL_FOLDERS_SCANNED' => 'اسکن فولدرها',
	'LBL_FROM' => 'از',
	'LBL_I_DONT_KNOW' => "نمیدانم",
	'LBL_IS_IN_RUNNING_STATE' => 'در مرحله اجرا', //Duplicated key-value pair
	'LBL_MAILBOX' => 'صندوق ایمیل ',
	'LBL_MAILCONVERTER_DESCRIPTION' => "Mail Converter enables you to configure your mailbox to scan your emails and create appropriate entities in Vtiger CRM.<br />You'll also need to define rules to specify what actions should be performed on your emails.<br />Your emails are scanned automatically, unless you've disabled Mail Scanner task in Scheduler. <br /><br /><br />",
	'LBL_MARK_MESSAGE_AS' => 'علامت گذاری پیام به عنوان',
	'LBL_MARK_MESSAGES_AS_READ' => 'علامت گذاری پیام به عنوان خوانده شده',
	'LBL_MARK_READ' => 'خوانده شده',
	'LBL_MATCH' => 'یکسا',
	'LBL_MAX_LIMIT_ONLY_TWO' => 'شما فقط میتوانید دو صندوق ایمیل را تنظیم کنید',
	'LBL_NEXT' => 'بعدی',
	'LBL_PRIORITY' => 'اولویت', //Duplicated key-value pair
	'LBL_RULE_DELETION_FAILED' => 'شکست در حذف قانون', //Duplicated key-value pair
	'LBL_RULE' => 'قانون',
	'LBL_RULES_LIST' => 'فهرست قوانین',
	'LBL_RULES_SEQUENCE_INFO_IS_EMPTY' => 'دنباله قانون خالی است', //Duplicated key-value pair
	'LBL_SAVED_SUCCESSFULLY' => 'ذخیره موفق',
	'LBL_SCANED_SUCCESSFULLY' => 'اسکن موفق',
	'LBL_SCANNED_SUCCESSFULLY' => 'اسکن موفق',
	'LBL_SCAN_NOW' => 'اسکن کن',
	'LBL_SELECT_FOLDERS' => 'انتخاب فولدرها',
	'LBL_SEQUENCE_UPDATED_SUCCESSFULLY' => 'به روزرسانی موفق',
	'LBL_STATUS_MESSAGE' => 'بررسی برای فعال سازی',
	'LBL_UNREAD_MESSAGES_FROM_LAST_SCAN' => 'پیام های خوانده نشده از آخرین اسکن',
	'LBL_UNSELECT_ALL' => 'عدم انتخاب همه',
	'LBL_UPDATE_FOLDERS' => 'به روزرسانی فولدرها',
	'LBL_VALIDATE_SSL_CERTIFICATE' => 'گواهی SSL معتبر است',
	'LINK_Accounts_FROM' => 'افزودن به سازمان [از]',
	'LINK_Accounts_TO' => 'افزودن به مخاطب [ به ]',
	'LINK_Contacts_FROM' => 'افزودن به مخاطب [ از ]',
	'LINK_Contacts_TO' => 'افزودن به مخاطب [ به ]',
	'LINK_Leads_FROM' => 'افزودن به سرنخ فروش [از]',
	'LINK_Leads_TO' => 'افزودن به سرنخ فروش [به]',
	'Look For'                     => 'گشتن برای'                    , 
	'MAILBOX_DETAILS' => 'جزییات صندوق ایمیل ',
	'MAILBOX' => 'صندوق ایمیل ',
	'MailConverter_Description' => 'تبدیل ایمیل ها به رکوردهای مربوطه',
	'MailConverter' => 'تبدیل ایمیل',
	'markas'                       => 'بعد از اسکن'                  ,
	'matchusing' => 'یکسان',
	'Not Contains' => 'شامل نیست',
	'Not Equals' => 'مساوی نیست',
	'Password'                     => 'کلمه عبور '                    , 
	'PRIORITISE_MESSAGE' => 'برای اولویت بندی قانون ها بلوک ها را گرفته و بکشید',
	'Protocol'                     => 'پروتکل'                    , 
	'Regex' => 'عبارت منظم',
	'RULE' => 'قانون',
	'Scanner Name'                 => 'نام اسکنر'                , 
	'SEEN' => 'خواندن',
	'SELECT_FOLDERS' => 'انتخاب فولدرها',
	'Server'                       => 'نام سرور'                 , 
	'SSL Method'                   => 'روش SSL'                  , 
	'SSL Type'                     => 'نوع SSL'                    , 
	'Status'                       => 'وضعیت '                      ,
	'subject' => 'عنوان',
	'Time Zone'                    => 'منطقه زمانی '                   ,
	'toaddress' => 'به',
	'TO_CHANGE_THE_FOLDER_SELECTION_DESELECT_ANY_OF_THE_SELECTED_FOLDERS' => 'برای تغییر فولدرهای انتخابی, انتخاب نکنید',
	'UNSEEN' => 'خوانده نشده',
	'UPDATE_HelpDesk_SUBJECT' => 'به روزرسانی تیکت',
	'User Name'                    => 'نام کاربری'                   , 
	'Validate SSL Certificate'     => 'گواهی SSL معتبر'    ,
);

$jsLanguageStrings = array(
	'JS_MAILBOX_DELETED_SUCCESSFULLY' => 'حذف موفق صندوق ایمیل ',
	'JS_MAILBOX_LOADED_SUCCESSFULLY' => 'بارگذاری موفق صندوق ایمیل ',
);	
