<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'ADD_CONDITIONS' => 'افزودن شرایط ',
	'ADD_TASKS' => 'افزودن وظیفه ',
	'Calendar' => 'انجام دادن',
	'LBL_ACTIVE' => 'فعال ',
	'LBL_ADD_FIELD' => 'افزودن فیلد', //Duplicated key-value pair
	'LBL_ADD_FIELDS' => 'افزودن فیلدها ',
	'LBL_ADD_TASKS_FOR_WORKFLOW' => 'افزودن وظیفه برای گردش کاری ',
	'LBL_ADD_TIME' => 'افزودن زمان',
	'LBL_ANNUAL_REVENUE' => 'annual_revenue',
	'LBL_ASSIGNED_TO' => 'واگذار شده به',
	'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'نمیتوان گردش کاری پیش فرض را حذف کرد',
	'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'This workflow was created in older look. Conditions created in older look cannot be edited. You can choose to recreate the conditions, or use the existing conditions without changing them.',
	'LBL_CREATING_WORKFLOW' => 'ایجاد گردش کاری ',
	'LBL_DUE_DATE' => 'مدت زمان',
	'LBL_EDITING_WORKFLOW' => 'ویرایش گردش کاری ',
	'LBL_ENABLE_REPEAT' => 'فعال کردن گزارش ',
	'LBL_ENABLE_TO_CREATE_FILTERS' => 'فعال کردن برای ایجاد فیلترها',
	'LBL_END_DATE' => 'تاریخ پایان ',
	'LBL_END_TIME' => 'زمان پایان ',
	'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'جزییات اساسی گردش کاری وارد کنید',
	'LBL_EVENT_NAME' => 'نام رویداد',
	'LBL_EXAMPLE_EXPRESSION' => 'تجربه ',
	'LBL_EXAMPLE_FIELD_NAME' => 'فیلد',
	'LBL_EXAMPLE_RAWTEXT' => 'Rawtext',
	'LBL_EXECUTE_TASK' => 'اجرای وظیفه ',
	'LBL_EXPRESSION_EXAMPLE2' => "if mailingcountry == 'India' then concat(firstname,' ',lastname) else concat(lastname,' ',firstname) end",
	'LBL_EXPRESSION' => 'تجربه ',
	'LBL_FIELD_NAME' => 'فیلد',
	'LBL_FINISH' => 'پایان ',
	'LBL_IN_ACTIVE' => 'فعال',
	'LBL_METHOD_NAME' => 'نام متد',
	'LBL_MODULES_TO_CREATE_RECORD' => 'ماژول ایجاد رکورد ',
	'LBL_NEW' => 'جدید',
	'LBL_NEXT' => 'بعدی',
	'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'برای این ماژول متدی وجود ندارد',
	'LBL_NO_TASKS_ADDED' => 'بدون وظیفه ',
	'LBL_NOTIFY_OWNER' => 'notify_owner',
	'LBL_PRIORITY' => 'اولویت ',
	'LBL_RAW_TEXT' => 'متن',
	'LBL_RECEPIENTS' => 'گیرنده',
	'LBL_RECREATE_CONDITIONS' => 'بازسازی شرایط',
	'LBL_SAVE_AND_CONTINUE' => 'ذخیره & ادامه ',
	'LBL_SELECT_OPTIONS' => 'انتخاب عملگرها',
	'LBL_SEND_NOTIFICATION' => 'ارسال هشدار ',
	'LBL_SET_FIELD_VALUES' => 'تنظیم مقدار فیلد',
	'LBL_SET_VALUE' => 'تخصیص مقدار ',
	'LBL_SMS_TEXT' => 'متن پیامک',
	'LBL_SPECIFY_WHEN_TO_EXECUTE' => 'زمان اجرای گردش کاری مشخص است',
	'LBL_START_DATE' => 'تاریخ شروع ',
	'LBL_START_TIME' => 'زمان شروع ',
	'LBL_STEP_1' => 'مرحله‌ 1',
	'LBL_TASK_TITLE' => 'عنوان وظیفه ',
	'LBL_TASK_TYPE' => 'نوع وظیفه ', //Duplicated key-value pair
	'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'مقدار یکسانی برای تاریخ شروع استفاده شده',
	'LBL_TIME' => 'زمان ',
	'LBL_TITLE' => 'عنوان ',
	'LBL_TYPE' => 'نوع',
	'LBL_USE_EXISTING_CONDITIONS' => 'استفاده از شرایط موجود ',
	'LBL_USE_FIELD' => 'استفاده از فیلد',
	'LBL_USE_FUNCTION' => 'استفاده از تابع',
	'LBL_VTIGER' => 'سیستم مدیریت مشتری ویتایگر',
	'LBL_WORKFLOW' => 'گردش کاری',
	'MANUAL' => 'سیستم ',
	'ONCE' => 'تا وقتی شرط درست باشد',
	'ON_EVERY_SAVE' => 'هربار رکورد ذخیره شود',
	'ON_FIRST_SAVE' => 'تنها در اولین ذخیره ',
	'ON_MODIFY' => 'هربار رکورد ویرایش شود',
	'SCHEDULE_WORKFLOW' => 'زمان بندی گردش کاری ',
        'ON_SCHEDULE'=>'زمان بندی ',
        'LBL_RUN_WORKFLOW' => 'اجرای گردش کاری ',
	'LBL_AT_TIME' => 'در زمان ',
	'LBL_HOURLY' => 'ساعتی',
	'LBL_DAILY' => 'روزانه',
	'LBL_WEEKLY' => 'هفتگی',
	'LBL_ON_THESE_DAYS' => 'در این روزها',
	'LBL_MONTHLY_BY_DATE' => 'ماهانه براساس تاریخ',
	'LBL_MONTHLY_BY_WEEKDAY' => 'ماهانه براساس هفته ',
	'LBL_YEARLY' => 'سالانه',
	'LBL_SPECIFIC_DATE' => 'در تاریخ مشخص ',
	'LBL_CHOOSE_DATE' => 'انتخاب تاریخ ',
	'LBL_SELECT_MONTH_AND_DAY' => 'انتخاب ماه و تاریخ ',
	'LBL_SELECTED_DATES' => 'تاریخ انتخابی',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'حداکثر حد مجاز',
	'LBL_NEXT_TRIGGER_TIME' => 'Next trigger time on',
	'LBL_MESSAGE' => 'پیام',
	 //Patch provided by http://trac.vtiger.com/cgi-bin/trac.cgi/ticket/7884
        'Workflows' => 'گردش کاری', 
        //Field names 
        'Summary' => 'خلاصه', 
        'Module' => 'ماژول', 
        'Execution Condition' => 'شرط اجرا',
);

$jsLanguageStrings = array(
	'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'فیلدهای مشابه انتخابی بیش از یک مورد هستند',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'تغییر موفق وضعیت ',
	'JS_TASK_DELETED_SUCCESSFULLY' => 'حذف موفق وظیفه ',
	'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'ذخیره موفق گردش کاری ',
);
