<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Big Problem'=>'مشکل بزرگ',
	'Closed'=>'بسته شده',
	'Contact Name' => 'نام مخاطب',
	'created' => 'ایجاد شده',
	'Critical'=>'بحرانی',
	'customer_portal' => 'در "پورتال مشتری" در ویتایگر ',
	'Days' => 'روزها',
	'Dear'=> 'عزیز',
	'Feature'=>'ویژگی',
	'From Portal' => 'از پورتال',
	'HelpDesk ID' => 'شناسه تیکت',
	'HelpDesk' => 'تیکت ها',
	'High'=>'بالا',
	'Hi' => 'سلام',
	'Hours' => 'ساعات',
	'LBL_ADD_RECORD' => 'افزودن تیکت',
	'LBL_ALTBODY' => 'This is the body in plain text for non-HTML mail clients',
	'LBL_CHECK_MAILID' => 'لطفا شناسه ایمیل خود را برای پورتال مشتری بررسی کنید',
	'LBL_CONVERT_FAQ' => 'تبدیل به سوال و جواب',
	'LBL_COULDNOT_CLOSED' => 'تیکت نمیتواند باشد',
	'LBL_CUSTOMER_COMMENTS' => 'مشتری اطلاعات اضافی زیر را به پاسخ شما اضافه کرده است',
	'LBL_CUSTOMER_PORTAL' => 'در پورتال مشتری - فوری',
	'LBL_DETAIL' => 'جزییات هستند :',
	'LBL_GIVE_MAILID' => 'لطفا شناسه ایمیل خود را وارد کنید',
	'LBL_LOGIN_DETAILS' => 'جزییات ورود به پورتال مشتری شما در زیر موجود است:',
	'LBL_LOGIN_REVOKED' => 'ورود ناموفق. با مدیر سیستم تماس بگیرید',
	'LBL_MAIL_COULDNOT_SENT' =>'ایمیل نمیتواند ارسال شود',
	'LBL_MAIL_SENT' => 'جزییات ورود به پورتال مشتری برای شناسه ایمیل شما ارسال شد',
	'LBL_PASSWORD' => 'کلمه عبور ：',
	'LBL_PORTAL_BODY_MAILINFO'=> 'تیکت هست',
	'LBL_RECORDS_LIST' => 'فهرست تیکت',
	'LBL_REGARDS'=> 'احترام',
	'LBL_RELATED_TO' => 'مربوط به',
	'LBL_RESPOND'=> 'پاسخ به تیکت بالا در سریع ترین زمان',
	'LBL_RESPONDTO_TICKETID' =>'پاسخ به شناسه تیکت',
	'LBL_RESPONSE_TO_TICKET_NUMBER' =>'پاسخ به شماره تیکت',
	'LBL_SEVERITY' => 'اهمیت',
	'LBL_STATUS_CLOSED' =>'بسته شده',//Do not convert this label. This is used to check the status. If the status 'Closed' is changed in vtigerCRM server side then you have to change in customerportal language file also.
	'LBL_STATUS' => 'وضعیت',
	'LBL_STATUS_UPDATE' => 'وضعیت تیکت به روز شد به',
	'LBL_SUBJECT_PORTAL_LOGIN_DETAILS' => 'جزییات ورود به پورتال مشتری',
	'LBL_SUBJECT' => 'عنوان :',
	'LBL_SUPPORT_ADMIN' => 'مدیر پشتیبانی',
	'LBL_TEAM'=> 'تیم پشتیبان ',
	'LBL_TICKET_DETAILS' => 'جزییات تیکت',
	'LBL_TICKET_INFORMATION' => 'اطلاعات تیکت',
	'LBL_TICKET_NUMBER' => 'شماره تیکت',
	'LBL_TICKET_RESOLUTION' => 'حل تیکت ',
	'LBL_USERNAME' => 'نام کاربری ：',
	'link' => 'شما میتوانید برای مشاهده پاسخ های ایجاد شده از لینک زیر استفاده کنید :',
	'Major'=>'بیشتر',
	'Minor'=>'کمتر',
	'Normal'=>'معمولی',
	'Open'=>'باز',
	'Other Problem'=>'سایر مشکل',
	'Related To' => 'مربوط به',
	'replied' => 'پاسخ داده شده',
	'reply'=>'پاسخ به',
	'Re' => 'Re :',
	'Severity' => 'اهمیت',
	'SINGLE_HelpDesk' => 'تیکت',
	'Small Problem'=>'مشکل کوچک',
	'Solution' => 'راه حل',
	'Support_team' => 'تیم پشتیبان ویتایگر ',
	'Thanks' => 'با تشکر',
	'The comments are' => 'نظرات هستند',
	'Ticket ID'=>'شناسه تیکت',
	'Ticket No' => 'شماره تیکت',
	'Ticket Title' => 'عنوان تیکت',
	'Title' => 'عنوان',
	'Update History' => 'به روزرسانی تاریخچه',
	'Urgent'=>'فوری',
	'Wait For Response'=>'در انتظار پاسخ',
);
