<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'300-Sales-Software'=>'300-Sales-Software',
	'301-Sales-Hardware'=>'301-Sales-Hardware',
	'302-Rental-Income'=>'302-Rental-Income',
	'303-Interest-Income'=>'303-Interest-Income',
	'304-Sales-Software-Support'=>'304-Sales-Software-Support',
	'305-Sales Other'=>'305-Sales Other',
	'306-Internet Sales'=>'306-Internet Sales',
	'307-Service-Hardware Labor'=>'307-Service-Hardware Labor',
	'308-Sales-Books'=>'308-Sales-Books',
	'Box'=>'جعبه',
	'Carton'=>'کارتن',
	'Caton'=>'کتون',
	'Commission Rate'=>'نرخ کمیسیون',
	'CRM Applications'=>'برنامه های مدیریت مشتری',
	'Dozen'=>'دو جین',
	'Each'=>'هر',
	'GL Account'=>'حساب GL',
	'Handler'=>'مربی',
	'Hardware'=>'سخت افزار',
	'Hours'=>'ساعات',
	'Impressions'=>'برداشت',
	'LBL_ADD_RECORD' => 'افزودن محصول',
	'LBL_ADD_TO_PRICEBOOKS' => 'افزودن به دفترچه قیمت', //Duplicated key-value pairs
	'Lb'=>'Lb',
	'LBL_CONVERSION_RATE' => 'نرخ تبدیل',
	'LBL_IMAGE_INFORMATION' => 'اطلاعات تصویر محصول',
	'LBL_MORE_CURRENCIES' => 'ارزهای بیشتر', 
	'LBL_PRICE' => 'قیمت',
	'LBL_PRICES' => 'قیمت های محصول',
	'LBL_PRODUCT_INFORMATION' => 'جزییات محصول',
    'LBL_PRODUCTSMOD_DISABLED' => 'فعال سازی ماژول محصولات برای مشاهده محصولات',
	'LBL_RECORDS_LIST' => 'فهرست محصولات',
	'LBL_RESET_PRICE' => 'بازنشانی قیمت',
	'LBL_RESET' => 'بازنشانی',
	'LBL_STOCK_INFORMATION' => 'اطلاعات انبار',
	'Manufacturer' => 'سازنده',
	'Mfr PartNo' => 'Mfr PartNo',
	'M'=>'M',
	'--None--'=>'--هیچ--',
	'Pack'=>'بسته',
	'Pages'=>'صفحات',
	'Part Number' => 'شماره قطعه',
	'Pieces'=>'قیمت ها',
	'Product Active' => 'محصول فعال',
	'Product Category' => 'دسته محصول',
	'Product Image'=>'تصویر محصول',
	'Product No' => 'شماره محصول',
	'Product Sheet'=>'برگه محصول',
	'Products' => 'محصولات',
	'Qty In Demand'=>'تعداد تقاضا',
	'Qty In Stock'=>'موجودی در انبار',
	'Qty/Unit'=>'تعداد/واحد',
	'Reams'=>'بند',
	'Reorder Level'=>'مرحله سفارش مجدد', //Duplicated key-value pairs
	'Serial No'=>'شماره سریال',
	'Sheet'=>'برگه',
	'SINGLE_Products' => 'محصول',
	'Software'=>'نرم افزار',
	'Spiral Binder'=>'بند اسپیرال',
	'Sq Ft'=>'Sq Ft',
	'Tax Class'=>'کلاس مالیات',
	'Unit Price'=>'قیمت واحد',
	'Usage Unit'=>'واحد استفاده شده',
	'Vendor PartNo' => 'شماره فروشنده', //Duplicated key-value pairs
	'Website' => 'وب سایت',
);
